default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
    -   id: flake8
        exclude: tests
        additional_dependencies: ["flake8-bugbear"]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    -   id: pyupgrade
        args: ["--py310-plus"]
